# Generated by Django 4.0.5 on 2022-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.TextField()),
                ('_Description', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
