# Generated by Django 4.0.5 on 2022-06-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_Description',
            new_name='Description',
        ),
    ]
