# Generated by Django 4.0.5 on 2022-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename__description_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tital',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
